/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Business;

/**
 *
 * @author siqiyang
 */
public class AssignJPanel extends javax.swing.JPanel {
    private Business business;
    /**
     * Creates new form AssignJPanel
     */
    public AssignJPanel(Business business) {
        initComponents();
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignBtn = new javax.swing.JButton();
        planBox = new javax.swing.JComboBox();
        applicantBox = new javax.swing.JComboBox();
        insuranceLabel = new javax.swing.JLabel();
        applicantLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assignBtn.setText("Assign Plan");
        add(assignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        add(planBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 160, -1));

        applicantBox.setToolTipText("");
        add(applicantBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 160, -1));

        insuranceLabel.setText("Insurance Plan");
        add(insuranceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        applicantLabel.setText("Applicant:");
        add(applicantLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox applicantBox;
    private javax.swing.JLabel applicantLabel;
    private javax.swing.JButton assignBtn;
    private javax.swing.JLabel insuranceLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox planBox;
    // End of variables declaration//GEN-END:variables
}
