/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Business;
import Model.InsurancePlans;
import javax.swing.JOptionPane;

/**
 *
 * @author siqiyang
 */
public class CreateInsurancePlanJPanel extends javax.swing.JPanel {
    
    private Business business;

    /**
     * Creates new form CreateInsurancePlanJPanel
     */
    public CreateInsurancePlanJPanel(Business business) {
        initComponents();
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        planIDField = new javax.swing.JTextField();
        monthCostField = new javax.swing.JTextField();
        planNameField = new javax.swing.JTextField();
        planIDLabel = new javax.swing.JLabel();
        createPlanBtn = new javax.swing.JButton();
        planNameLabel = new javax.swing.JLabel();
        costPerMonthLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(planIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 140, -1));
        add(monthCostField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 140, -1));
        add(planNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 140, -1));

        planIDLabel.setText("Plan ID");
        add(planIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        createPlanBtn.setText("Add Plan");
        createPlanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPlanBtnActionPerformed(evt);
            }
        });
        add(createPlanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        planNameLabel.setText("Plan Name");
        add(planNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        costPerMonthLabel.setText("Cost Per Month");
        add(costPerMonthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 100, 20));

        jLabel1.setText("Create Insurance Plan");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 260, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void createPlanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPlanBtnActionPerformed
        // TODO add your handling code here:
        
        InsurancePlans insurancePlans = this.business.getInsuranceplan();
        // read the text fields
        
        String id = planIDField.getText();
        String planName = planNameField.getText();
        String monthCost = monthCostField.getText();
        
        // convert/cast and pass

        insurancePlans.createPlans(Integer.valueOf(id), planName, Double.valueOf(monthCost));
        JOptionPane.showMessageDialog(null, "Added Plans");
    }//GEN-LAST:event_createPlanBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel costPerMonthLabel;
    private javax.swing.JButton createPlanBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField monthCostField;
    private javax.swing.JTextField planIDField;
    private javax.swing.JLabel planIDLabel;
    private javax.swing.JTextField planNameField;
    private javax.swing.JLabel planNameLabel;
    // End of variables declaration//GEN-END:variables
}
