/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Applicant;
import Model.ApplicantsDirectory;
import Model.Business;
import Model.InsurancePlans;
import Model.Pet;
import Model.PlanDetails;
import Model.Vaccine;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author siqiyang
 */
public class CreateApplicantJPanel extends javax.swing.JPanel {
    private Business business;
    private Boolean isnull = false;
    Applicant applicant;
    /**
     * Creates new form CreateApplicantJPanel
     */
    public CreateApplicantJPanel(Business business) {
        initComponents();
        this.business=business;
        
        populateDropdown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lastNameField = new javax.swing.JTextField();
        applicantIDField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        applicantIDLabel = new javax.swing.JLabel();
        petGenderLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        vaccinecompletionLabel = new javax.swing.JLabel();
        petBreedField = new javax.swing.JTextField();
        petBreedLabel = new javax.swing.JLabel();
        petNameLabel = new javax.swing.JLabel();
        petNameField = new javax.swing.JTextField();
        petAgeLabel = new javax.swing.JLabel();
        petAgeField = new javax.swing.JTextField();
        petTypeLabel = new javax.swing.JLabel();
        petTypeField = new javax.swing.JTextField();
        vaccineNameLabel = new javax.swing.JLabel();
        vaccineNameField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        lastNameLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        petGenderComboBox = new javax.swing.JComboBox();
        vaccineCompletionComboBox = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        insuranceComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 120, -1));

        applicantIDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                applicantIDFieldFocusLost(evt);
            }
        });
        add(applicantIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 120, -1));

        dateLabel.setText("Application Date: ");
        add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        applicantIDLabel.setText("Applicant ID");
        add(applicantIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        petGenderLabel.setText("Pet Gender:");
        add(petGenderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));
        add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 120, -1));

        firstNameLabel.setText("Applicant First Name: ");
        add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        vaccinecompletionLabel.setText("Vaccine completion:");
        add(vaccinecompletionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));
        add(petBreedField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 120, -1));

        petBreedLabel.setText("Pet Breed:");
        add(petBreedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        petNameLabel.setText("Pet Name:");
        add(petNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        add(petNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 120, -1));

        petAgeLabel.setText("Pet Age:");
        add(petAgeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));
        add(petAgeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 120, -1));

        petTypeLabel.setText("Pet Type:");
        add(petTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        add(petTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 120, -1));

        vaccineNameLabel.setText("Vaccine Name:");
        add(vaccineNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));
        add(vaccineNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 120, -1));

        addBtn.setText("Add Applicant");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        titleLabel.setText("Create Applicant");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 220, 30));

        lastNameLabel1.setText("Applicant Last Name: ");
        add(lastNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jDateChooser1.setDateFormatString("MM-dd-yyyy");
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 120, -1));

        petGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Female", "Male" }));
        add(petGenderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 120, -1));

        vaccineCompletionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
        add(vaccineCompletionComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 110, -1));

        jButton2.setText("Add Vaccine");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        add(insuranceComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 160, -1));

        jLabel1.setText("Assign Insurance");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Insurance Information:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 170, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Pet's Information:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("Pet's Vaccine details:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 170, -1));

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("*Enter \"No\" for name if not inject any vaccine");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 290, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        ApplicantsDirectory applicantsDirectory = this.business.getApplicantdirectory();

        String id = applicantIDField.getText();
        String firstName = firstNameField.getText();
        String lastName= lastNameField.getText();
        Date date = jDateChooser1.getDate();

        String petName =petNameField.getText();
        String petAge =petAgeField.getText();
        String petGender =(String) petGenderComboBox.getSelectedItem();
        String petType =petTypeField.getText();
        String petBreed =petBreedField.getText();

        String vaccineName = vaccineNameField.getText();
        String completion = (String) vaccineCompletionComboBox.getSelectedItem();
        PlanDetails plan = (PlanDetails) insuranceComboBox.getSelectedItem();


        if(id.equals("")||firstName.equals("")||lastName.equals("")||date==null|| petName.equals("")||petAge.equals("")||petGender==null||
               petType.equals("")||petBreed.equals("")||vaccineName.equals("")||completion==null||plan==null){
            this.isnull = true;
            JOptionPane.showMessageDialog(null, "Pleae fill all fields");  
            
        } else {
            
        
        boolean i=this.business.getApplicantdirectory().checkApplicationIDUnique(Integer.valueOf(id));
        
        if(i){
             Pet pet = new Pet(petName,Integer.valueOf(petAge),petGender,petType,petBreed);

            this.applicant = applicantsDirectory.createApplicant(Integer.valueOf(id), firstName, lastName, date, pet);
            
            Boolean isCompleted;
            if (completion.equals("Yes") ){
                isCompleted = true;   
            }else{
                isCompleted=false;
            }

            applicant.setPet(pet);
            pet.setOwner(applicant);
            pet.createVaccineDetails(vaccineName, isCompleted);
           
            applicant.setPlan(plan);
 
            JOptionPane.showMessageDialog(null, "Applicant Created");
            
        }else{
            JOptionPane.showMessageDialog(null, "ID already exist");
            applicantIDField.setText("");
       
        }            
           
        
        }

    }//GEN-LAST:event_addBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String name = vaccineNameField.getText();
        String completion = (String) vaccineCompletionComboBox.getSelectedItem();
        
        this.applicant.getPet().createVaccineDetails(name, toBoolean(completion));
        JOptionPane.showMessageDialog(null, "Vaccine Added");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void applicantIDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_applicantIDFieldFocusLost
        // TODO add your handling code here:
        String id =applicantIDField.getText();
        
        boolean i=this.business.getApplicantdirectory().checkApplicationIDUnique(Integer.valueOf(id));
        
        if(i){
            
        }else{
            JOptionPane.showMessageDialog(null, "re-enter");
            applicantIDField.setText("");
        }
    }//GEN-LAST:event_applicantIDFieldFocusLost
    
    
    public void populateDropdown(){
        ArrayList<PlanDetails> plans = this.business.getInsuranceplan().getPlans();
        
        for(PlanDetails p: plans){
            insuranceComboBox.addItem(p);
        }
    }
    
    public boolean toBoolean(String completion){
        if(completion.equals("Yes")){
            return true;
        }else{
            return false;
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField applicantIDField;
    private javax.swing.JLabel applicantIDLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JComboBox insuranceComboBox;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel1;
    private javax.swing.JTextField petAgeField;
    private javax.swing.JLabel petAgeLabel;
    private javax.swing.JTextField petBreedField;
    private javax.swing.JLabel petBreedLabel;
    private javax.swing.JComboBox petGenderComboBox;
    private javax.swing.JLabel petGenderLabel;
    private javax.swing.JTextField petNameField;
    private javax.swing.JLabel petNameLabel;
    private javax.swing.JTextField petTypeField;
    private javax.swing.JLabel petTypeLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox vaccineCompletionComboBox;
    private javax.swing.JTextField vaccineNameField;
    private javax.swing.JLabel vaccineNameLabel;
    private javax.swing.JLabel vaccinecompletionLabel;
    // End of variables declaration//GEN-END:variables
}
