/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.LibrarianWorkArea;

import AppSystem.ApplicationSystem;
import AppSystem.Branch;
import Library.Author.Author;
import Library.Genre.Genre;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author siqiyang
 */
public class AddMaterialJPanel extends javax.swing.JPanel {
    private UserAccount useraccount;
    private Branch branch;
    private ApplicationSystem appSystem;
    /**
     * Creates new form AddMaterialJPanel
     */
    public AddMaterialJPanel(ApplicationSystem appSystem, Branch branch, UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.branch= branch;
        this.appSystem = appSystem;
        this.useraccount = useraccount;
        
        populateAuthorDropdown();
        populateGenreDropdown();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addMagazineBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        noOfPagesField = new javax.swing.JTextField();
        languageField = new javax.swing.JTextField();
        typeOfBindingField = new javax.swing.JTextField();
        authorField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        registeredDateField = new javax.swing.JTextField();
        companyNameField = new javax.swing.JTextField();
        issueTypeField = new javax.swing.JTextField();
        genreTypeField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        genreDropdown = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        authorDropdown = new javax.swing.JComboBox();
        addAuthorBtn = new javax.swing.JButton();
        addGenreBtn = new javax.swing.JButton();
        addBookBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("language");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        addMagazineBtn.setText("Add Magazin");
        addMagazineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMagazineBtnActionPerformed(evt);
            }
        });
        add(addMagazineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        jLabel3.setText("GenreType");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel4.setText("Type Of Binding");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel5.setText("author");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));
        add(noOfPagesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 110, -1));
        add(languageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 110, -1));
        add(typeOfBindingField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 110, -1));
        add(authorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 100, -1));

        jLabel6.setText("No. Of Pages");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        nameLabel.setText("name");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel9.setText("registeredDate");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 110, -1));
        add(registeredDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 110, -1));
        add(companyNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 110, -1));
        add(issueTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 110, -1));
        add(genreTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 100, -1));

        jLabel8.setText("company Name");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel11.setText("Issue Type");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        add(genreDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 120, -1));

        jLabel12.setText("author");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel13.setText("GenreType");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        add(authorDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 120, -1));

        addAuthorBtn.setText("Add Author");
        addAuthorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAuthorBtnActionPerformed(evt);
            }
        });
        add(addAuthorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        addGenreBtn.setText("Add Genre");
        addGenreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGenreBtnActionPerformed(evt);
            }
        });
        add(addGenreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        addBookBtn.setText("Add Book");
        addBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookBtnActionPerformed(evt);
            }
        });
        add(addBookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addMagazineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMagazineBtnActionPerformed
        // TODO add your handling code here:
        if(registeredDateField.getText().equals("")||nameField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Pleae fill Date and Name to add magazine");  
        } else {        
            String registeredDate =registeredDateField.getText();
            String name =nameField.getText();

            String companyName =companyNameField.getText();
            String issueType =issueTypeField.getText();


            branch.getLibrary().getGeneralDirectory().createMagazine( name, Integer.valueOf(registeredDate), companyName, issueType);
            JOptionPane.showMessageDialog(null, "Magazine Added");
        }
    }//GEN-LAST:event_addMagazineBtnActionPerformed

    private void addAuthorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAuthorBtnActionPerformed
        // TODO add your handling code here:
        String author=authorField.getText();
        branch.getLibrary().getAuthorDirectory().createAuthor(author);
        JOptionPane.showMessageDialog(null, "Author Added");        
        populateAuthorDropdown();
        
    }//GEN-LAST:event_addAuthorBtnActionPerformed

    private void addGenreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGenreBtnActionPerformed
        // TODO add your handling code here:
        String genre=genreTypeField.getText();
        branch.getLibrary().getGenreDirectory().createGenre(genre);
        JOptionPane.showMessageDialog(null, "Genre Added");
        populateGenreDropdown();
    }//GEN-LAST:event_addGenreBtnActionPerformed

    private void addBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookBtnActionPerformed
        // TODO add your handling code here:
        if(registeredDateField.getText().equals("")||nameField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Pleae fill Date and Name to add book");  
        } else {
            String registeredDate =registeredDateField.getText();
            String name =nameField.getText();
            String noOfPages =noOfPagesField.getText();
            String language =languageField.getText();
            String typeOfBinding =typeOfBindingField.getText();
            Author author=(Author) authorDropdown.getSelectedItem();
            Genre genretype= (Genre) genreDropdown.getSelectedItem();

            branch.getLibrary().getBookDirectory().createBook(name, Integer.valueOf(registeredDate),Integer.valueOf( noOfPages), language, typeOfBinding, author, genretype);

            JOptionPane.showMessageDialog(null, "Book Added");
        }
        
    }//GEN-LAST:event_addBookBtnActionPerformed
    public void populateAuthorDropdown(){
        ArrayList<Author> author = this.branch.getLibrary().getAuthorDirectory().getAuthorList();
        
        for(Author au: author){
           authorDropdown.addItem(au);
        }
    }
    
    public void populateGenreDropdown(){
        ArrayList<Genre> genre = this.branch.getLibrary().getGenreDirectory().getGenreList();
        
        for(Genre gen: genre){
           genreDropdown.addItem(gen);
        }
    }    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAuthorBtn;
    private javax.swing.JButton addBookBtn;
    private javax.swing.JButton addGenreBtn;
    private javax.swing.JButton addMagazineBtn;
    private javax.swing.JComboBox authorDropdown;
    private javax.swing.JTextField authorField;
    private javax.swing.JTextField companyNameField;
    private javax.swing.JComboBox genreDropdown;
    private javax.swing.JTextField genreTypeField;
    private javax.swing.JTextField issueTypeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField languageField;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField noOfPagesField;
    private javax.swing.JTextField registeredDateField;
    private javax.swing.JTextField typeOfBindingField;
    // End of variables declaration//GEN-END:variables
}
