/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.LibrarianWorkArea;

import AppSystem.ApplicationSystem;
import AppSystem.Branch;
import Customer.Customer;
import Library.Book.Book;
import Library.General.Magazine;
import Library.Library;
import RentalService.RentalRequest;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author siqiyang
 */
public class RentalRequestManagementJPanel extends javax.swing.JPanel {
    private UserAccount useraccount;
    private ApplicationSystem appSystem;
    DefaultTableModel historytableModel;
    private Library branchlibrary;
    private Book book; 
    private Magazine magazine;
    private RentalRequest rr;
    /**
     * Creates new form RentalRequestManagement
     */
    public RentalRequestManagementJPanel() {
        initComponents();
    }
    
    RentalRequestManagementJPanel(ApplicationSystem appSystem, Branch branch, UserAccount useraccount) {
        initComponents();
        this.setVisible(true);

        this.appSystem = appSystem;
        this.useraccount = useraccount;
        this.branchlibrary = branch.getLibrary();

        this.historytableModel=(DefaultTableModel)rentalHistoryTable.getModel();

        displayHistory();
        

    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rentalHistoryTable = new javax.swing.JTable();
        accepteBtn = new javax.swing.JButton();
        statusComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rentalHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Status", "Price", "Rent Duration", "book", "magazin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        rentalHistoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rentalHistoryTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(rentalHistoryTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 530, 160));

        accepteBtn.setText("ok");
        accepteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accepteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(accepteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Approve", "Reject" }));
        jPanel1.add(statusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, -1));

        jLabel1.setText("Status:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accepteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accepteBtnActionPerformed
        // TODO add your handling code here:

        int selectedRow = rentalHistoryTable.getSelectedRow();
        RentalRequest rr= (RentalRequest) rentalHistoryTable.getValueAt(selectedRow, 0);
        if(selectedRow >= 0) {
           rr.setStatus((String) statusComboBox.getSelectedItem());
           if(statusComboBox.getSelectedItem().equals("Approve")&& rr.getBook()!=null){
               rr.getBook().setIsAvailablityFlag(false);}
           if(statusComboBox.getSelectedItem().equals("Approve")&& rr.getMagazine()!=null){   
               rr.getMagazine().setIsAvailablityFlag(false);
            } 
        }

        if(selectedRow >= 0) {
           rr.setStatus((String) statusComboBox.getSelectedItem());
           if(statusComboBox.getSelectedItem().equals("Reject")&& rr.getBook()!=null){
               //book.setIsAvailablityFlag(true); rr.getbook==null
               rr.getBook().setIsAvailablityFlag(true);
           } 
           if(statusComboBox.getSelectedItem().equals("Reject")&& rr.getMagazine()!=null){
               //book.setIsAvailablityFlag(true); rr.getbook==null
               rr.getMagazine().setIsAvailablityFlag(true);      
           }    
        }
        displayHistory();
        
      
    }//GEN-LAST:event_accepteBtnActionPerformed

    private void rentalHistoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentalHistoryTableMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_rentalHistoryTableMouseClicked
    public void displayHistory(){
        historytableModel.setRowCount(0);
        for(Customer c: this.appSystem.getCustomerDirectory().getCustomerList()) {
        ArrayList<RentalRequest> rentalrequests= c.getRentalrequest();
        
        if(rentalrequests.size()>0){
                       
            
            for (RentalRequest rr:rentalrequests){
               if(rr.getLib().equals(this.branchlibrary)) {
                Object row[] = new Object[6];
                row[0] = rr;
                row[1] = rr.getStatus();
                row[2]= rr.getPrice();
                row[3]= rr.getDuration();
                row[4] = rr.getBook();
                row[5] = rr.getMagazine();
                
                historytableModel.addRow(row);
                
              }
            }
 
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accepteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable rentalHistoryTable;
    private javax.swing.JComboBox statusComboBox;
    // End of variables declaration//GEN-END:variables
}
