/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import UserAccount.UserAccountDirectory;
import AppSystem.ApplicationSystem;
import AppSystem.Branch;
import Role.Role;
import UserAccount.UserAccount;
import javax.swing.JOptionPane;

/**
 *
 * @author siqiyang
 */
public class MainJFrame extends javax.swing.JFrame {
        private ApplicationSystem appSystem; 
        private Branch branch;
        private UserAccount useraccount;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
       
        initComponents();
        this.appSystem = ApplicationSystem.getInstance();
        

    }
    
    
    public MainJFrame(ApplicationSystem appSystem, Branch branch, UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        
        this.appSystem = appSystem;
        this.branch = branch;
        this.useraccount = useraccount;
        

    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        userNameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        userNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));
        jPanel1.add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 160, -1));
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 160, -1));

        userNameLabel.setText("User Name");
        jPanel1.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
       Boolean foundUser = false;
        
        if(this.appSystem.getSystemAdminAccount().authenticateUser(passwordField.getText(), passwordField.getText()) != null) {
            UserAccount user = this.appSystem.getSystemAdminAccount().authenticateUser(passwordField.getText(), passwordField.getText());
            foundUser = true;
            user.getRole().createWorkArea(appSystem, branch, user);
            this.setVisible(false);
        } else {
            for(Branch branch: this.appSystem.getBranches()) {
                if(branch.getBranchuseraccountDirectory().authenticateUser(passwordField.getText(), userNameField.getText()) != null) {
                    UserAccount branchUser = branch.getBranchuseraccountDirectory().authenticateUser(passwordField.getText(), userNameField.getText());
                    foundUser = true;
                    branchUser.getRole().createWorkArea(appSystem, branch, branchUser);
                    this.setVisible(false);
                }
            }
        }
        // if user not found
        if(!foundUser) {
            JOptionPane.showMessageDialog(null, "Invalid Credentials");
        }
                
    }//GEN-LAST:event_loginBtnActionPerformed
//    public void populateDropdown() {
//        comboBoxRole.removeAllItems();
//        
//        for(String rolename: Role.getRoles()) {
//            comboBoxRole.addItem(rolename);
//        }
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
