/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminWorkArea;

import UserAccount.UserAccountDirectory;
import AppSystem.ApplicationSystem;
import AppSystem.Branch;
import Customer.Customer;
import Customer.CustomerDirectory;
import Role.CustomerRole;
import Role.Role;
import UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author siqiyang
 */
public class CustomerManagementJPanel extends javax.swing.JPanel {
    private UserAccount useraccount;
    private ApplicationSystem appSystem;
    DefaultTableModel tableModel;
    /**
     * Creates new form CustomerJPanel
     */
    public CustomerManagementJPanel() {
        initComponents();
    }
    
    CustomerManagementJPanel(ApplicationSystem appSystem, Branch branch, UserAccount useraccount) {
        initComponents();
        
        this.appSystem = appSystem;
        this.useraccount = useraccount;
        this.tableModel = (DefaultTableModel) jTable1.getModel();
        
        populate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fieldusername = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JTextField();
        fieldname = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        userNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(fieldusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 120, 30));
        jPanel1.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 120, 30));
        jPanel1.add(fieldname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 120, 30));

        addBtn.setText("ADD CUSTOMER");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Password", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 430, 250));

        userNameLabel.setText("User Name");
        jPanel1.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        passwordLabel.setText("Password");
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        nameLabel.setText("Name");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1035, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:

        
        UserAccountDirectory ua = this.appSystem.getSystemAdminAccount();
//        for( UserAccount u :ua.getUseraccountList() ) {
//            System.out.println(u.getUserName());
//            System.out.println(u.getPassword()); 
//        }
        
        Boolean foundDuplicate = false;
        if(ua.accountExists(fieldusername.getText(), fieldPassword.getText())) {
            foundDuplicate = true;
            JOptionPane.showMessageDialog(null, "Sorry credentials are taken.");
        }
            
        
        for(Branch branch: this.appSystem.getBranches()){
            UserAccountDirectory uad = branch.getBranchuseraccountDirectory();
        
            if(uad.accountExists(fieldusername.getText(), fieldPassword.getText())) {
                foundDuplicate = true;
                JOptionPane.showMessageDialog(null, "Sorry credentials are taken.");
                break;
            }

        }
//        if(ua.accountExists(fieldusername.getText(), fieldPassword.getText())) {
//            JOptionPane.showMessageDialog(null, "Sorry credentials are taken.");
//        }
        if(foundDuplicate == false){
            // save the customer obj for user and useraccount credentials
            
            UserAccount user = this.appSystem.getSystemAdminAccount().createUserAccount(fieldusername.getText(), fieldPassword.getText(), new CustomerRole());
            this.appSystem.getCustomerDirectory().createCustomer(user.getAccountId(), fieldname.getText());
            JOptionPane.showMessageDialog(null, "Customer Created");
            populate();
        }
              
        

        
    }//GEN-LAST:event_addBtnActionPerformed

    public void populate() {
        tableModel.setRowCount(0);
        for(Customer c: this.appSystem.getCustomerDirectory().getCustomerList()) {
            UserAccount u = this.appSystem.getSystemAdminAccount().findById(c.getId());
            
            Object[] row = new Object[4];
            
            row[0] = c.getId();
            row[1] = c.getName();
            row[2] = u.getUserName();
            row[3] = u.getPassword();
            
            tableModel.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField fieldPassword;
    private javax.swing.JTextField fieldname;
    private javax.swing.JTextField fieldusername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
