/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminWorkArea;

import UserAccount.UserAccountDirectory;
import AppSystem.ApplicationSystem;
import AppSystem.Branch;
import Customer.Customer;
import Customer.CustomerDirectory;
import Library.Employee.EmployeeDirectory;
import Library.Library;
import Role.BranchAdminRole;
import Role.LibrarianRole;
import Role.Role;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author siqiyang
 */
public class EmployeeManagementJPanel extends javax.swing.JPanel {
    private UserAccount useraccount;
    private ApplicationSystem appSystem;
    private Branch branch;
    DefaultTableModel tableModel;
    /**
     * Creates new form CustomerJPanel
     */
    public EmployeeManagementJPanel() {
        initComponents();
    }
    
    EmployeeManagementJPanel(ApplicationSystem appSystem, Branch branch, UserAccount useraccount) {
        initComponents();
        
        this.appSystem = appSystem;
        this.useraccount = useraccount;
        this.tableModel = (DefaultTableModel) jTable1.getModel();
        
        populateDesignation();   
        populateBranchDropdown();
        populate();
        
    }
    
    public void populateDesignation() {
   
        designationComboBox.addItem("Branch Manager");
        designationComboBox.addItem("Librarian");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fieldusername = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        userNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        designationLabel = new javax.swing.JLabel();
        experienceLabel = new javax.swing.JLabel();
        fieldexperience = new javax.swing.JTextField();
        designationComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        userNameLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(fieldusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 120, 30));
        jPanel1.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 120, 30));

        addBtn.setText("Add Employee");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Branch", "Library", "ID", "Name", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 430, 250));

        userNameLabel.setText("name");
        jPanel1.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        passwordLabel.setText("Password");
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        designationLabel.setText("Designation");
        jPanel1.add(designationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        experienceLabel.setText("Experience");
        jPanel1.add(experienceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        jPanel1.add(fieldexperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 120, 30));

        jPanel1.add(designationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 100, -1));

        jLabel1.setText("Assign Library");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 100, -1));

        userNameLabel1.setText("User Name");
        jPanel1.add(userNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        Boolean foundDuplicate = false;
        for(Branch branch: this.appSystem.getBranches()){
            UserAccountDirectory ua = branch.getBranchuseraccountDirectory();
        
            if(ua.accountExists(fieldusername.getText(), fieldPassword.getText())) {
                foundDuplicate = true;
                JOptionPane.showMessageDialog(null, "Sorry credentials are taken.");
                break;
            }
            
        }
        if(foundDuplicate == false) {
            Library lib= (Library) jComboBox1.getSelectedItem(); 
            Branch branch = this.appSystem.getBranchforLib(lib);

 
            //boolean i=this.branch.getLibrary().getEmployeDirectory().checkEmployeeUnique(Integer.valueOf(user.getAccountId())); 
            if(designationComboBox.getSelectedItem().equals("Branch Manager") ){
            
            UserAccount user= branch.getBranchuseraccountDirectory().createUserAccount(fieldusername.getText(), fieldPassword.getText(), new BranchAdminRole());
            lib.getEmployeDirectory().createEmployee(Integer.valueOf(fieldexperience.getText()), (String) designationComboBox.getSelectedItem(), nameField.getText(), user.getAccountId());
   
            
            }else{
            UserAccount userac=branch.getBranchuseraccountDirectory().createUserAccount(fieldusername.getText(), fieldPassword.getText(), new LibrarianRole());
            lib.getEmployeDirectory().createEmployee(Integer.valueOf(fieldexperience.getText()), (String) designationComboBox.getSelectedItem(), nameField.getText(), userac.getAccountId());
            }

            populate();
        }
      

        

        
    }//GEN-LAST:event_addBtnActionPerformed
    public void populateBranchDropdown(){
        ArrayList<Branch> branches = this.appSystem.getBranches();
        
        for(Branch br: branches){
           jComboBox1.addItem(br.getLibrary());
        }
    }
    
    
    
    public void populate() {
        
        tableModel.setRowCount(0);
        for(Branch br: this.appSystem.getBranches()) {
            for(UserAccount u: br.getBranchuseraccountDirectory().getUseraccountList()){
                
   
            Object[] row = new Object[6];
            
            row[0] = br;
            row[1] = br.getLibrary();                    
            row[2] = u.getAccountId();
            row[3] = br.getLibrary().getEmployeDirectory().getEmployeeId(u.getAccountId());
            row[4] =u.getUserName();
            row[5] =u.getPassword();
            
            tableModel.addRow(row);
        }
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox<String> designationComboBox;
    private javax.swing.JLabel designationLabel;
    private javax.swing.JLabel experienceLabel;
    private javax.swing.JTextField fieldPassword;
    private javax.swing.JTextField fieldexperience;
    private javax.swing.JTextField fieldusername;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel userNameLabel1;
    // End of variables declaration//GEN-END:variables
}
