/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Address;
import Model.Contact;
import Model.Person;

/**
 *
 * @author Nidhi Raghavendra
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Person person;

    
    public MainJFrame() {
        initComponents();
        
        this.person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        CreateJPanel = new javax.swing.JPanel();
        firstName = new javax.swing.JTextField();
        fieldStreet = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        nameLabel3 = new javax.swing.JLabel();
        addresslabel4 = new javax.swing.JLabel();
        officePhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        permStreet1 = new javax.swing.JTextField();
        localPhone1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        officeEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        personalEmail1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        nuID = new javax.swing.JTextField();
        schoolID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        collegename = new javax.swing.JTextField();
        aptno = new javax.swing.JTextField();
        permAptNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        currentcitystate = new javax.swing.JLabel();
        permCityState = new javax.swing.JLabel();
        currentzip = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        currentCitystate = new javax.swing.JTextField();
        permCitystate = new javax.swing.JTextField();
        currentZipcode = new javax.swing.JTextField();
        permZipcode = new javax.swing.JTextField();
        viewCollegeName = new javax.swing.JPanel();
        viewFirstName = new javax.swing.JLabel();
        viewStreet = new javax.swing.JLabel();
        viewPermAddre = new javax.swing.JLabel();
        viewPersonalPhone = new javax.swing.JLabel();
        viewOfficePhone = new javax.swing.JLabel();
        viewLastName = new javax.swing.JLabel();
        viewID = new javax.swing.JLabel();
        viewcollgename = new javax.swing.JLabel();
        viewCurrentAptNo = new javax.swing.JLabel();
        viewPermAptNo = new javax.swing.JLabel();
        viewZipCode = new javax.swing.JLabel();
        viewPermZipCode = new javax.swing.JLabel();
        viewCurrentCityState = new javax.swing.JLabel();
        viewPermCityState = new javax.swing.JLabel();
        viewPersonalEmail = new javax.swing.JLabel();
        viewOffieEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreateJPanel.setBackground(new java.awt.Color(204, 204, 255));
        CreateJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CreateJPanel.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 110, 30));
        CreateJPanel.add(fieldStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 124, 36));

        SaveBtn.setText("SAVE");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        CreateJPanel.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, -1, -1));

        nameLabel3.setText("firstName");
        CreateJPanel.add(nameLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        addresslabel4.setText("Permanent street");
        CreateJPanel.add(addresslabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));
        CreateJPanel.add(officePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 130, 31));

        jLabel5.setText("Street Name");
        CreateJPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        CreateJPanel.add(permStreet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 130, 31));
        CreateJPanel.add(localPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 130, 31));

        jLabel6.setText("Office Phone");
        CreateJPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel7.setText("Personal Phone");
        CreateJPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));
        CreateJPanel.add(officeEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 130, 31));

        jLabel8.setText("Office Email");
        CreateJPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));
        CreateJPanel.add(personalEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 130, 31));

        jLabel9.setText("Personal Email");
        CreateJPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        jLabel1.setText("Last Name");
        CreateJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        CreateJPanel.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 110, 30));
        CreateJPanel.add(nuID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, -1));

        schoolID.setText("NUID");
        CreateJPanel.add(schoolID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel2.setText("College Name");
        CreateJPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));
        CreateJPanel.add(collegename, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 120, -1));

        aptno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aptnoActionPerformed(evt);
            }
        });
        CreateJPanel.add(aptno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 110, -1));
        CreateJPanel.add(permAptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 130, -1));

        jLabel3.setText("Current Apt No.");
        CreateJPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel4.setText("Permanent AptNo.");
        CreateJPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        currentcitystate.setText("Current City/state");
        CreateJPanel.add(currentcitystate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        permCityState.setText("Permanent City/State");
        CreateJPanel.add(permCityState, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        currentzip.setText("Zipcode");
        CreateJPanel.add(currentzip, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel10.setText("Permanent Zipcode");
        CreateJPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));
        CreateJPanel.add(currentCitystate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 100, -1));
        CreateJPanel.add(permCitystate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 110, -1));
        CreateJPanel.add(currentZipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 140, -1));
        CreateJPanel.add(permZipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 120, -1));

        jSplitPane1.setLeftComponent(CreateJPanel);

        viewCollegeName.setBackground(new java.awt.Color(255, 204, 204));
        viewCollegeName.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewFirstName.setText("waiting for input");
        viewCollegeName.add(viewFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 100, 20));

        viewStreet.setText("waiting for input");
        viewCollegeName.add(viewStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        viewPermAddre.setText("waiting for input");
        viewCollegeName.add(viewPermAddre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        viewPersonalPhone.setText("waiting for input");
        viewCollegeName.add(viewPersonalPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        viewOfficePhone.setText("waiting for input");
        viewCollegeName.add(viewOfficePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        viewLastName.setText("waiting for input");
        viewCollegeName.add(viewLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        viewID.setText("waiting for input");
        viewCollegeName.add(viewID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        viewcollgename.setText("waiting for input");
        viewCollegeName.add(viewcollgename, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        viewCurrentAptNo.setText("waiting for input");
        viewCollegeName.add(viewCurrentAptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        viewPermAptNo.setText("waiting for input");
        viewCollegeName.add(viewPermAptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        viewZipCode.setText("waiting for input");
        viewCollegeName.add(viewZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        viewPermZipCode.setText("waiting for input");
        viewCollegeName.add(viewPermZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        viewCurrentCityState.setText("waiting for input");
        viewCollegeName.add(viewCurrentCityState, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        viewPermCityState.setText("waiting for input");
        viewCollegeName.add(viewPermCityState, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        viewPersonalEmail.setText("waiting for input");
        viewCollegeName.add(viewPersonalEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        viewOffieEmail.setText("waiting for input");
        viewCollegeName.add(viewOffieEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        jSplitPane1.setRightComponent(viewCollegeName);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        String firstname = firstName.getText();
        String lastnamelabel = lastname.getText();
        String nuidlabel = nuID.getText();
        String collegenamelabel = collegename.getText();
        String street = fieldStreet.getText();
        String permStreet = permStreet1.getText();
        String aptnolabel =aptno.getText();
        String permaptnolabel = permAptNo.getText();
        String citystatelable = currentCitystate.getText();
        String permcitystatelable = permCitystate.getText();
        String ziplable =currentZipcode.getText();
        String permziplable = permZipcode.getText();
        long localPhone = Long.valueOf(localPhone1.getText());
        long offPhone = Long.valueOf(officePhone.getText());
        String personalEmail = personalEmail1.getText();
        String offEmail = officeEmail.getText();
        
        this.person.setFirstName(firstname);
        Person obj2 = new Person();
        
        Address address = this.person.getAddress();
        address.setStreet(street);
        address.setAptNo(aptnolabel);
        address.setStateorcity(street);
        address.setZipcode(ziplable);
        
                
        Address permanentAddress = this.person.getPermanentAddress();
        permanentAddress.setStreet(permStreet);
        permanentAddress.setAptNo(permaptnolabel);
        permanentAddress.setStateorcity(permcitystatelable);
        permanentAddress.setZipcode(permziplable);
        
        Contact officeContact = this.person.getOfficeContact();
        officeContact.setPhoneNumber(offPhone);
        officeContact.setEmailID(offEmail);
        
        Contact locatContact = this.person.getPersonalContact();
        locatContact.setPhoneNumber(localPhone);
        locatContact.setEmailID(personalEmail);
        
        display();
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void aptnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aptnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aptnoActionPerformed

    private void display() {
        viewFirstName.setText(this.person.getFirstName());
        viewLastName.setText(this.person.getLastName());
        viewID.setText(this.person.getNuid());
        viewcollgename.setText(this.person.getCollegeName());
        
        viewStreet.setText(this.person.getAddress().getStreet());
        viewPermAddre.setText(this.person.getPermanentAddress().getStreet());
        viewCurrentAptNo.setText(this.person.getAddress().getAptNo());
        viewPermAptNo.setText(this.person.getPermanentAddress().getAptNo());
        viewCurrentCityState.setText(this.person.getAddress().getStateorcity());
        viewPermCityState.setText(this.person.getPermanentAddress().getStateorcity());
        viewZipCode.setText(this.person.getAddress().getZipcode());
        viewPermZipCode.setText(this.person.getPermanentAddress().getZipcode());
        
        
        viewPersonalPhone.setText(String.valueOf(this.person.getPersonalContact().getPhoneNumber()));
        viewOfficePhone.setText(String.valueOf(this.person.getPersonalContact().getPhoneNumber()));
        
        viewPersonalEmail.setText(this.person.getPersonalContact().getEmailID());
        viewOffieEmail.setText(this.person.getOfficeContact().getEmailID());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateJPanel;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel addresslabel4;
    private javax.swing.JTextField aptno;
    private javax.swing.JTextField collegename;
    private javax.swing.JTextField currentCitystate;
    private javax.swing.JTextField currentZipcode;
    private javax.swing.JLabel currentcitystate;
    private javax.swing.JLabel currentzip;
    private javax.swing.JTextField fieldStreet;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField localPhone1;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JTextField nuID;
    private javax.swing.JTextField officeEmail;
    private javax.swing.JTextField officePhone;
    private javax.swing.JTextField permAptNo;
    private javax.swing.JLabel permCityState;
    private javax.swing.JTextField permCitystate;
    private javax.swing.JTextField permStreet1;
    private javax.swing.JTextField permZipcode;
    private javax.swing.JTextField personalEmail1;
    private javax.swing.JLabel schoolID;
    private javax.swing.JPanel viewCollegeName;
    private javax.swing.JLabel viewCurrentAptNo;
    private javax.swing.JLabel viewCurrentCityState;
    private javax.swing.JLabel viewFirstName;
    private javax.swing.JLabel viewID;
    private javax.swing.JLabel viewLastName;
    private javax.swing.JLabel viewOfficePhone;
    private javax.swing.JLabel viewOffieEmail;
    private javax.swing.JLabel viewPermAddre;
    private javax.swing.JLabel viewPermAptNo;
    private javax.swing.JLabel viewPermCityState;
    private javax.swing.JLabel viewPermZipCode;
    private javax.swing.JLabel viewPersonalEmail;
    private javax.swing.JLabel viewPersonalPhone;
    private javax.swing.JLabel viewStreet;
    private javax.swing.JLabel viewZipCode;
    private javax.swing.JLabel viewcollgename;
    // End of variables declaration//GEN-END:variables
}
