/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Business;
import Model.InsurancePlans;
import javax.swing.JOptionPane;

/**
 *
 * @author siqiyang
 */
public class CreateInsurancePlanJPanel extends javax.swing.JPanel {
    
    private Business business;
    private Boolean isnull = false;

    /**
     * Creates new form CreateInsurancePlanJPanel
     */
    public CreateInsurancePlanJPanel(Business business) {
        initComponents();
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        planIDField = new javax.swing.JTextField();
        planNameField = new javax.swing.JTextField();
        planIDLabel = new javax.swing.JLabel();
        createPlanBtn = new javax.swing.JButton();
        planNameLabel = new javax.swing.JLabel();
        costPerMonthLabel1 = new javax.swing.JLabel();
        monthCostField1 = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        planIDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                planIDFieldFocusLost(evt);
            }
        });
        add(planIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 140, -1));
        add(planNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 140, -1));

        planIDLabel.setText("Plan ID");
        add(planIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        createPlanBtn.setText("Add Plan");
        createPlanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPlanBtnActionPerformed(evt);
            }
        });
        add(createPlanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        planNameLabel.setText("Plan Name");
        add(planNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        costPerMonthLabel1.setText("Cost Per Month");
        add(costPerMonthLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 100, 20));
        add(monthCostField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 140, -1));

        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        titleLabel.setText("Create Plan");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 220, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void createPlanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPlanBtnActionPerformed
        // TODO add your handling code here:
        
        InsurancePlans insurancePlans = this.business.getInsuranceplan();
               
        String id = planIDField.getText();
        String planName = planNameField.getText();
        String monthCost = monthCostField1.getText();
        
        if(id.equals("")||planName.equals("")||monthCost.equals("")){
            this.isnull = true;
            JOptionPane.showMessageDialog(null, "Pleae fill all fields");      
        } else {
            boolean i=this.business.getInsuranceplan().checkInsuranceIDUnique(Integer.valueOf(id));
            if(i){
                insurancePlans.createPlans(Integer.valueOf(id), planName, Double.valueOf(monthCost));
                JOptionPane.showMessageDialog(null, "Added Plans");            

        }else{
            JOptionPane.showMessageDialog(null, "ID already exist");
            planIDField.setText("");
        }
        }
        

            
    }//GEN-LAST:event_createPlanBtnActionPerformed

    private void planIDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_planIDFieldFocusLost
        // TODO add your handling code here:
        String id =planIDField.getText();
        
        boolean i=this.business.getInsuranceplan().checkInsuranceIDUnique(Integer.valueOf(id));
        
        if(i){
            
        }else{
            JOptionPane.showMessageDialog(null, "ID already exist");
            planIDField.setText("");
        }
    }//GEN-LAST:event_planIDFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel costPerMonthLabel1;
    private javax.swing.JButton createPlanBtn;
    private javax.swing.JTextField monthCostField1;
    private javax.swing.JTextField planIDField;
    private javax.swing.JLabel planIDLabel;
    private javax.swing.JTextField planNameField;
    private javax.swing.JLabel planNameLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
