/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Business;
/**
 *
 * @author siqiyang
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    Business business;
    
    public MainJFrame() {
        initComponents();
        
        this.business = new Business();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ControlJPanel = new javax.swing.JPanel();
        createApplicantBtn = new javax.swing.JButton();
        viewApplicationBtn = new javax.swing.JButton();
        createInsuranceBtn = new javax.swing.JButton();
        updateInsuranceBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setBackground(new java.awt.Color(204, 255, 255));

        ControlJPanel.setBackground(new java.awt.Color(0, 204, 204));
        ControlJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createApplicantBtn.setText("Create Application");
        createApplicantBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createApplicantBtnActionPerformed(evt);
            }
        });
        ControlJPanel.add(createApplicantBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 184, -1, -1));

        viewApplicationBtn.setText("View Application");
        viewApplicationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewApplicationBtnActionPerformed(evt);
            }
        });
        ControlJPanel.add(viewApplicationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 249, 137, -1));

        createInsuranceBtn.setText("Create Insurance");
        createInsuranceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createInsuranceBtnActionPerformed(evt);
            }
        });
        ControlJPanel.add(createInsuranceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 55, 137, -1));

        updateInsuranceBtn.setText("Update Insurance");
        updateInsuranceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInsuranceBtnActionPerformed(evt);
            }
        });
        ControlJPanel.add(updateInsuranceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 114, -1, -1));

        jSplitPane1.setLeftComponent(ControlJPanel);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jSplitPane1.setRightComponent(jPanel1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createInsuranceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createInsuranceBtnActionPerformed
        // TODO add your handling code here:
        CreateInsurancePlanJPanel creatInsurancePlanJPanel = new CreateInsurancePlanJPanel(business);
        jSplitPane1.setRightComponent(creatInsurancePlanJPanel);
    }//GEN-LAST:event_createInsuranceBtnActionPerformed

    private void updateInsuranceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInsuranceBtnActionPerformed
        // TODO add your handling code here:
        UpdateInsuranceJPanel updateInsuranceJPanel = new UpdateInsuranceJPanel(business);
        jSplitPane1.setRightComponent(updateInsuranceJPanel);
    }//GEN-LAST:event_updateInsuranceBtnActionPerformed

    private void viewApplicationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewApplicationBtnActionPerformed
        // TODO add your handling code here:
        UpdateApplicantJPanel updateApplicantJPanel = new UpdateApplicantJPanel(business);
        jSplitPane1.setRightComponent(updateApplicantJPanel);
    }//GEN-LAST:event_viewApplicationBtnActionPerformed

    private void createApplicantBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createApplicantBtnActionPerformed
        // TODO add your handling code here:
        CreateApplicantJPanel createApplicantJPanel = new CreateApplicantJPanel(business);
        jSplitPane1.setRightComponent(createApplicantJPanel);      
    }//GEN-LAST:event_createApplicantBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlJPanel;
    private javax.swing.JButton createApplicantBtn;
    private javax.swing.JButton createInsuranceBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton updateInsuranceBtn;
    private javax.swing.JButton viewApplicationBtn;
    // End of variables declaration//GEN-END:variables
}
