/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.BranchManagerWorkArea;

import AppSystem.ApplicationSystem;
import AppSystem.Branch;
import Customer.Customer;
import Library.Book.Book;
import Library.General.Magazine;
import Library.Library;
import RentalService.RentalRequest;
import UI.MainJFrame;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author siqiyang
 */
public class BranchManagerJFrame extends javax.swing.JFrame {
    private  ApplicationSystem appSystem;   
    private  Branch branch;
    private  UserAccount useraccount;
    private Library library;
    private Book book; 
    private Magazine magazine;
    private RentalRequest rentalrequest;

    DefaultTableModel booktableModel;
    DefaultTableModel magazinetableModel;
    DefaultTableModel historytableModel;
    /**
     * Creates new form BranchManagerJFrame
     */

    
    public BranchManagerJFrame(ApplicationSystem appSystem, Branch branch, UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.appSystem = appSystem;
        this.branch = branch;
        this.useraccount = useraccount;
        
        this.booktableModel = (DefaultTableModel) bookTable.getModel();
        this.magazinetableModel = (DefaultTableModel) magazinelTable.getModel();
        this.historytableModel=(DefaultTableModel)rentalHistoryTable.getModel();
        
        branchName.setText(branch.getName());
        totalRevenueField.setText(String.valueOf(branch.totalRevenue()));
        
        displayBookInfo();
        displayHistory();
        displayMagazineInfo();
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        branchName = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        magazinelTable = new javax.swing.JTable();
        totalRevenueField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        rentalHistoryTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        branchName.setText("jLabel1");
        jPanel1.add(branchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        magazinelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Branch", "Library", "Serieal Number", "Magazine Name", "Avaliablity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        magazinelTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                magazinelTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(magazinelTable);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 500, 120));
        jPanel1.add(totalRevenueField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, 100, -1));

        jLabel1.setText("Total Revenue:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, -1, -1));

        jLabel2.setText("Branch Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Branch", "Library", "Serieal Number", "Book Name", "Avaliablity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bookTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 460, 150));

        rentalHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Status", "Price", "Rent Duration", "book", "magazin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        rentalHistoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rentalHistoryTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(rentalHistoryTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 530, 160));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainJFrame(appSystem, branch, useraccount);
    }//GEN-LAST:event_backBtnActionPerformed

    private void magazinelTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_magazinelTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = magazinelTable.getSelectedRow();
        if(selectedRow >= 0) {
            this.magazine=  (Magazine) magazinelTable.getValueAt(selectedRow, 2);
            this.library=(Library) magazinelTable.getValueAt(selectedRow, 1);
        }
    }//GEN-LAST:event_magazinelTableMouseClicked

    private void bookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = bookTable.getSelectedRow();
        if(selectedRow >= 0) {
            this.book= (Book) booktableModel.getValueAt(selectedRow, 2);
            this.library=(Library) booktableModel.getValueAt(selectedRow, 1);
        }
    }//GEN-LAST:event_bookTableMouseClicked

    private void rentalHistoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentalHistoryTableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_rentalHistoryTableMouseClicked
    public void displayBookInfo() {

        if(branch.getLibrary().getBookDirectory().getBookList().size()>0){
            booktableModel.setRowCount(0);

                for(Book b:branch.getLibrary().getBookDirectory().getBookList()){
                    Object row[] = new Object[5];
                    row[0] = branch;
                    row[1] = branch.getLibrary();
                    row[2]= b;
                    row[3] = b.getName();
                    row[4] = b.isIsAvailablityFlag();
        
                    booktableModel.addRow(row);
                }
               
        } else {
            System.out.print("");
        }
    }
    public void displayMagazineInfo() {
        
        if(branch.getLibrary().getGeneralDirectory().getMagazineList().size()>0){
            magazinetableModel.setRowCount(0);

                for (Magazine m:branch.getLibrary().getGeneralDirectory().getMagazineList()){
                    Object row[] = new Object[5];
                    row[0] = branch;
                    row[1] = branch.getLibrary();
                    row[2]= m;
                    row[3] = m.getName();
                    row[4] = m.isIsAvailablityFlag();

                    magazinetableModel.addRow(row);
                }          
        } else {
            System.out.print("");
        }
    }
    
    public void displayHistory(){
        for(Customer c: this.appSystem.getCustomerDirectory().getCustomerList()) {
        ArrayList<RentalRequest> rentalrequests= c.getRentalrequest();
        
        if(rentalrequests.size()>0){
                       
            historytableModel.setRowCount(0);
            for (RentalRequest rr:rentalrequests){
               if(rr.getLib().equals(this.branch.getLibrary())) {
                Object row[] = new Object[6];
                row[0] = rr;
                row[1] = rr.getStatus();
                row[2]= rr.getPrice();
                row[3]= rr.getDuration();
                row[4] = rr.getBook();
                row[5] = rr.getMagazine();
                
                historytableModel.addRow(row);
                
              }
            }
 
            }
        }
    }    
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BranchManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BranchManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BranchManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BranchManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new BranchManagerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable bookTable;
    private javax.swing.JLabel branchName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable magazinelTable;
    private javax.swing.JTable rentalHistoryTable;
    private javax.swing.JTextField totalRevenueField;
    // End of variables declaration//GEN-END:variables
}
