/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Model.Person;
import Model.Contact;
import Model.Recipe;
import java.awt.Image;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author siqiyang
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Person person;
    private Boolean validate = false;
    private String picture = "";
    
    public CreateJPanel(Person person) {
        initComponents();
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNamejLabel = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        lastNamejLabel = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        userNamejLabel = new javax.swing.JLabel();
        emailIDjLabel = new javax.swing.JLabel();
        emailId = new javax.swing.JTextField();
        phonejLabel = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        recipeTitlejLabel = new javax.swing.JLabel();
        recipeTitle = new javax.swing.JTextField();
        noOfServingsjLabel = new javax.swing.JLabel();
        noOfServings = new javax.swing.JTextField();
        isGlutenFreejLabel = new javax.swing.JLabel();
        isGlutenFree = new javax.swing.JTextField();
        difficultyLeveljLabel = new javax.swing.JLabel();
        difficultylv = new javax.swing.JTextField();
        categoryOfFoodjLabel = new javax.swing.JLabel();
        categoryOfFood = new javax.swing.JTextField();
        noOfIngredientsjLabel = new javax.swing.JLabel();
        noOfIngredients = new javax.swing.JTextField();
        descriptionjLabel = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        recipePicturejLabel = new javax.swing.JLabel();
        saveRecipeBtn = new javax.swing.JButton();
        imageUploadBtn = new javax.swing.JButton();
        phonemessage = new javax.swing.JLabel();
        headtitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(203, 203, 119));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstNamejLabel.setText("Chef’s First Name");
        add(firstNamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 20));

        firstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameFocusLost(evt);
            }
        });
        firstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNameKeyTyped(evt);
            }
        });
        add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 77, 80, -1));

        lastNamejLabel.setText("Chef’s Last Name");
        add(lastNamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 20));

        lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameFocusLost(evt);
            }
        });
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        lastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lastNameKeyPressed(evt);
            }
        });
        add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 80, -1));

        userName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameFocusLost(evt);
            }
        });
        add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 77, 80, -1));

        userNamejLabel.setText("Username");
        add(userNamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 60, 20));

        emailIDjLabel.setText("Email ID");
        add(emailIDjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 50, 20));

        emailId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailIdFocusLost(evt);
            }
        });
        add(emailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 80, -1));

        phonejLabel.setText("Phone Number");
        add(phonejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 90, 20));

        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFocusLost(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneKeyPressed(evt);
            }
        });
        add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 77, 80, -1));

        recipeTitlejLabel.setText("Recipe Title");
        add(recipeTitlejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        recipeTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeTitleActionPerformed(evt);
            }
        });
        add(recipeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 107, -1));

        noOfServingsjLabel.setText("No. of Servings");
        add(noOfServingsjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        noOfServings.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                noOfServingsFocusLost(evt);
            }
        });
        noOfServings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfServingsActionPerformed(evt);
            }
        });
        add(noOfServings, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 107, -1));

        isGlutenFreejLabel.setText("Is Gluten Free ");
        add(isGlutenFreejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        isGlutenFree.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                isGlutenFreeFocusLost(evt);
            }
        });
        isGlutenFree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isGlutenFreeActionPerformed(evt);
            }
        });
        add(isGlutenFree, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 107, -1));

        difficultyLeveljLabel.setText("Difficulty Level ");
        add(difficultyLeveljLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        difficultylv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                difficultylvFocusLost(evt);
            }
        });
        difficultylv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultylvActionPerformed(evt);
            }
        });
        add(difficultylv, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 107, -1));

        categoryOfFoodjLabel.setText("Category of Food");
        add(categoryOfFoodjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        categoryOfFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryOfFoodActionPerformed(evt);
            }
        });
        add(categoryOfFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 107, -1));

        noOfIngredientsjLabel.setText("No. of Ingredients");
        add(noOfIngredientsjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        noOfIngredients.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                noOfIngredientsFocusLost(evt);
            }
        });
        noOfIngredients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfIngredientsActionPerformed(evt);
            }
        });
        add(noOfIngredients, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 107, -1));

        descriptionjLabel.setText("Description");
        add(descriptionjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionActionPerformed(evt);
            }
        });
        add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 107, -1));

        recipePicturejLabel.setBackground(new java.awt.Color(204, 204, 0));
        add(recipePicturejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 180, 120));

        saveRecipeBtn.setText("Save Recipe");
        saveRecipeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRecipeBtnActionPerformed(evt);
            }
        });
        add(saveRecipeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        imageUploadBtn.setText("Upload Images");
        imageUploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageUploadBtnActionPerformed(evt);
            }
        });
        add(imageUploadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        phonemessage.setForeground(new java.awt.Color(255, 0, 0));
        add(phonemessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 150, 20));

        headtitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        headtitle.setText("Create Recipe ");
        add(headtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void recipeTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recipeTitleActionPerformed

    private void noOfServingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfServingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfServingsActionPerformed

    private void isGlutenFreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isGlutenFreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isGlutenFreeActionPerformed

    private void difficultylvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultylvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_difficultylvActionPerformed

    private void categoryOfFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryOfFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryOfFoodActionPerformed

    private void noOfIngredientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfIngredientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfIngredientsActionPerformed

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionActionPerformed

    private void imageUploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageUploadBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
        
        if(showOpenDialogue ==JFileChooser.APPROVE_OPTION){
            File selectedImageFile = browseImageFile.getSelectedFile();
            String recipePicture = selectedImageFile.getAbsolutePath(); // recipeobj.getrecipture
            
            // check if recipePicture is empty or null \
            
            JOptionPane.showMessageDialog(null,recipePicture);
            
            ImageIcon ii= new ImageIcon(recipePicture);
            
            Image image = ii.getImage().getScaledInstance(recipePicturejLabel.getWidth(), recipePicturejLabel.getHeight(),Image.SCALE_SMOOTH);
            
            recipePicturejLabel.setIcon(new ImageIcon(image));
            
          //  this.person.getRecipe().setRecipePicture(recipePicture);
            
            // allowing acces to picture path to the rest of the class methods
            picture = recipePicture;
    
        }
        
    }//GEN-LAST:event_imageUploadBtnActionPerformed

    private void saveRecipeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRecipeBtnActionPerformed
        // TODO add your handling code here
        
        String fistName1 = firstName.getText();
        String lastName1 = lastName.getText();
        String userName1 = userName.getText();
        
        String emailId1 = emailId.getText();
        String phoneNo =phone.getText();
        
        this.person.setFirstName(fistName1);
        this.person.setLastName(lastName1);
        this.person.setUserName(userName1);
        
        
        Contact contact = this.person.getContact();
        contact.setEmailId(emailId1);
        contact.setPhone(Long.valueOf(phoneNo));
        
        String recipeTitle1 = recipeTitle.getText();
        String categoryOfFood1 = categoryOfFood.getText();
        String noOfServings1 = noOfServings.getText();
        String isGlutenFree1 = isGlutenFree.getText();
        String difficultylv1 = difficultylv.getText();
        String noOfIngredients1 = noOfIngredients.getText();
        String description1 = description.getText();
        String recipePhoto1= picture;
        
        
        
        if(fistName1.isBlank()||lastName1.isBlank()||userName1.isBlank()||emailId1.isBlank()||phoneNo.isBlank()||recipeTitle1.isBlank()|| categoryOfFood1.isBlank() || description1.isBlank()||noOfServings1.isBlank()
                ||isGlutenFree1.isBlank()|| difficultylv1.isBlank()||noOfIngredients1.isBlank()||recipePhoto1.isBlank()){
        this.validate = true;
            JOptionPane.showMessageDialog(null, "Pleae fill all fields");
        } else {
                    
                Recipe recipe = this.person.getRecipe();
                recipe.setRecipeTitle(recipeTitle1);
                recipe.setCategoryOfFood(categoryOfFood1);
                recipe.setDescription(description1);
                recipe.setDifficultyLevel(Double.valueOf(difficultylv1));
                recipe.setNoOfIngredient(Integer.valueOf(noOfIngredients1));
                recipe.setNoOfServings(Integer.valueOf(noOfServings1));
                recipe.setIsGlutenFree(Boolean.valueOf(isGlutenFree1));
                recipe.setRecipePicture(picture);
                
        
                JOptionPane.showMessageDialog(null, "Information Saved");
                       
            // 
        
        }
        
        
    }//GEN-LAST:event_saveRecipeBtnActionPerformed

    private void firstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameKeyTyped

    private void firstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameKeyPressed
        // TODO add your handling code here:
//        String PATTERN="^[a-zA-Z]{0,30}$";
//        Pattern patt = Pattern.compile(PATTERN);
//        Matcher match = patt.matcher(firstName.getText());
//        if(!match.matches()){
//            fnm.setText("Naming Incorrect! ");
//        }else {
//            fnm.setText(null);       
//        }
    }//GEN-LAST:event_firstNameKeyPressed

    private void phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyPressed
        // TODO add your handling code here:
//        char c = evt.getKeyChar();
//        Pattern pattern = Pattern.compile("^\\d{10}$");
//        Matcher matcher = pattern.matcher(phone.getText());
//
//        if(Character.isLetter(c)||matcher.matches()){
//            phone.setEditable(false);
//            phonemessage.setText("Numbers Only or Exceed length");
//        }else
//        {
//            phone.setEditable(true);
//        }
    }//GEN-LAST:event_phoneKeyPressed

    private void lastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameKeyPressed

    private void firstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFocusLost
        // TODO add your handling code here:
        
        if(firstName.getText().isEmpty()) {
            
            this.validate = true;
            
        } else {
            if(firstName.getText().matches("[a-zA-Z]+")) {
                this.validate = false;
            } else {
                this.validate = true;
                firstName.setText("");
            }
        }
    }//GEN-LAST:event_firstNameFocusLost

    private void userNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFocusLost
        // TODO add your handling code here:
        if(userName.getText().isEmpty()) {
            // error
            
            this.validate = true;
            
        } else {
            if(userName.getText().matches("[a-zA-Z0-9]+")) {
                this.validate = false;
            } else {
                this.validate = true;
                userName.setText("");
            }
        }
    }//GEN-LAST:event_userNameFocusLost

    private void lastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFocusLost
        // TODO add your handling code here:
        if(lastName.getText().isEmpty()) {
            // error
            
            this.validate = true;
            
        } else {
            if(lastName.getText().matches("[a-zA-Z]+")) {
                this.validate = false;
            } else {
                this.validate = true;
                lastName.setText("");
            }
        }
    }//GEN-LAST:event_lastNameFocusLost

    private void phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusLost
        // TODO add your handling code here:
        if(phone.getText().isEmpty()) {
            // error
            
            this.validate = true;
            
        } else {
            if(phone.getText().matches("[0-9]{10}")) {
                this.validate = false;
            } else {
                this.validate = true;
                phone.setText("");
            }
        }
    }//GEN-LAST:event_phoneFocusLost

    private void noOfServingsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_noOfServingsFocusLost
        // TODO add your handling code here:
        if(noOfServings.getText().isEmpty()) {
            // error
            
            this.validate = true;
            
        } else {
            if(noOfServings.getText().matches("\\d+")) {
                this.validate = false;
            } else {
                this.validate = true;
                noOfServings.setText("");
            }
        }
    }//GEN-LAST:event_noOfServingsFocusLost

    private void isGlutenFreeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_isGlutenFreeFocusLost
        // TODO add your handling code here:
                if(isGlutenFree.getText().isEmpty()) {
            // error
            
            this.validate = true;
            
        } else {
            if(isGlutenFree.getText().equalsIgnoreCase("true") ||isGlutenFree.getText().equalsIgnoreCase("false")  ) {
                this.validate = false;
            } else {
                this.validate = true;
                isGlutenFree.setText("");
            }
        }
    }//GEN-LAST:event_isGlutenFreeFocusLost

    private void emailIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailIdFocusLost
        // TODO add your handling code here:
        if(emailId.getText().isEmpty()) {
            // error
            
            this.validate = true;
            
        } else {
            if(emailId.getText().matches("[a-zA-Z0-9]+@[a-zA-Z]+(.com)")) {
                this.validate = false;
            } else {
                this.validate = true;
                emailId.setText("");
            }
        }
    }//GEN-LAST:event_emailIdFocusLost

    private void difficultylvFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_difficultylvFocusLost
        // TODO add your handling code here:
        if(difficultylv.getText().isEmpty()) {
            // error
            
            this.validate = true;
            
        } else {
            if(difficultylv.getText().matches("\\d+")) {
                this.validate = false;
            } else {
                this.validate = true;
                difficultylv.setText("");
            }
        }
    }//GEN-LAST:event_difficultylvFocusLost

    private void noOfIngredientsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_noOfIngredientsFocusLost
        // TODO add your handling code here:
         if(noOfIngredients.getText().isEmpty()) {
            // error
            
            this.validate = true;
            
        } else {
            if(noOfIngredients.getText().matches("\\d+")) {
                this.validate = false;
            } else {
                this.validate = true;
                noOfIngredients.setText("");
            }
        }
    }//GEN-LAST:event_noOfIngredientsFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categoryOfFood;
    private javax.swing.JLabel categoryOfFoodjLabel;
    private javax.swing.JTextField description;
    private javax.swing.JLabel descriptionjLabel;
    private javax.swing.JLabel difficultyLeveljLabel;
    private javax.swing.JTextField difficultylv;
    private javax.swing.JLabel emailIDjLabel;
    private javax.swing.JTextField emailId;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel firstNamejLabel;
    private javax.swing.JLabel headtitle;
    private javax.swing.JButton imageUploadBtn;
    private javax.swing.JTextField isGlutenFree;
    private javax.swing.JLabel isGlutenFreejLabel;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lastNamejLabel;
    private javax.swing.JTextField noOfIngredients;
    private javax.swing.JLabel noOfIngredientsjLabel;
    private javax.swing.JTextField noOfServings;
    private javax.swing.JLabel noOfServingsjLabel;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phonejLabel;
    private javax.swing.JLabel phonemessage;
    private javax.swing.JLabel recipePicturejLabel;
    private javax.swing.JTextField recipeTitle;
    private javax.swing.JLabel recipeTitlejLabel;
    private javax.swing.JButton saveRecipeBtn;
    private javax.swing.JTextField userName;
    private javax.swing.JLabel userNamejLabel;
    // End of variables declaration//GEN-END:variables
}
