/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Model.Contact;
import Model.Person;
import Model.Recipe;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author siqiyang
 */
public class ReadJPanel extends javax.swing.JPanel {
    
    private Person person;

    /**
     * Creates new form ReadJPanel
     * @param person
     */
    public ReadJPanel(Person person) {
        initComponents();
        this.person =person;
        displayPerson(person);
    }
    
        private void displayPerson(Person person){
        String firstName1 = person.getFirstName();
        firstName.setText(firstName1);
        
        String lastName1 = person.getLastName();
        lastName.setText(lastName1);
        
        String username = person.getUserName();
        userName.setText(username);
        
        Contact contact = this.person.getContact();
        emailId.setText(contact.getEmailId());
        phone.setText(String.valueOf(contact.getPhone()));
        
        Recipe recipe = this.person.getRecipe();
        String recipeTitle1 = recipe.getRecipeTitle();
        recipeTitle.setText(recipeTitle1);
        String categoryOfFood1 = recipe.getCategoryOfFood();
        categoryOfFood.setText(categoryOfFood1);
        String description1 = recipe.getCategoryOfFood();
        description.setText(description1);
        
        noOfServings.setText(String.valueOf(recipe.getNoOfServings()));
        difficultylv.setText(String.valueOf(recipe.getDifficultyLevel()));
        noOfIngredients.setText(String.valueOf(recipe.getNoOfIngredient()));
        isGlutenFree.setText(String.valueOf(recipe.getIsGlutenFree()));
        
        String recipePicture1 =recipe.getRecipePicture();
                         
ImageIcon ii= new ImageIcon(recipePicture1);
Image image = ii.getImage().getScaledInstance(120, 100,Image.SCALE_SMOOTH);
recipePicturejLabel.setIcon(new ImageIcon(image));
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        firstNamejLabel = new javax.swing.JLabel();
        lastNamejLabel = new javax.swing.JLabel();
        emailId = new javax.swing.JTextField();
        emailIDjLabel = new javax.swing.JLabel();
        userNamejLabel = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        phonejLabel = new javax.swing.JLabel();
        categoryOfFood = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        recipePicturejLabel = new javax.swing.JLabel();
        noOfIngredients = new javax.swing.JTextField();
        noOfIngredientsjLabel = new javax.swing.JLabel();
        difficultylv = new javax.swing.JTextField();
        difficultyLeveljLabel = new javax.swing.JLabel();
        isGlutenFreejLabel = new javax.swing.JLabel();
        isGlutenFree = new javax.swing.JTextField();
        noOfServings = new javax.swing.JTextField();
        noOfServingsjLabel = new javax.swing.JLabel();
        recipeTitlejLabel = new javax.swing.JLabel();
        recipeTitle = new javax.swing.JTextField();
        descriptionjLabel = new javax.swing.JLabel();
        categoryOfFoodjLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(137, 173, 182));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(145, 195, 208));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstName.setEnabled(false);
        jPanel1.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 35, 85, -1));

        lastName.setEnabled(false);
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        jPanel1.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 70, 85, -1));

        firstNamejLabel.setText("Chef’s First Name");
        jPanel1.add(firstNamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 38, -1, -1));

        lastNamejLabel.setText("Chef’s Last Name");
        jPanel1.add(lastNamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 73, -1, -1));

        emailId.setEnabled(false);
        jPanel1.add(emailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 70, 85, -1));

        emailIDjLabel.setText("Email ID");
        jPanel1.add(emailIDjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 73, -1, -1));

        userNamejLabel.setText("Username");
        jPanel1.add(userNamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 38, -1, -1));

        userName.setEnabled(false);
        jPanel1.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 35, 85, -1));

        phone.setEnabled(false);
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 35, 85, -1));

        phonejLabel.setText("Phone Number");
        jPanel1.add(phonejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 38, -1, -1));

        categoryOfFood.setEnabled(false);
        categoryOfFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryOfFoodActionPerformed(evt);
            }
        });
        jPanel1.add(categoryOfFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 107, -1));

        description.setEnabled(false);
        description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionActionPerformed(evt);
            }
        });
        jPanel1.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 107, -1));
        jPanel1.add(recipePicturejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 180, 120));

        noOfIngredients.setEnabled(false);
        noOfIngredients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfIngredientsActionPerformed(evt);
            }
        });
        jPanel1.add(noOfIngredients, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 107, -1));

        noOfIngredientsjLabel.setText("No. of Ingredients");
        jPanel1.add(noOfIngredientsjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        difficultylv.setEnabled(false);
        difficultylv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultylvActionPerformed(evt);
            }
        });
        jPanel1.add(difficultylv, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 107, -1));

        difficultyLeveljLabel.setText("Difficulty Level ");
        jPanel1.add(difficultyLeveljLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        isGlutenFreejLabel.setText("Is Gluten Free ");
        jPanel1.add(isGlutenFreejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        isGlutenFree.setEnabled(false);
        isGlutenFree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isGlutenFreeActionPerformed(evt);
            }
        });
        jPanel1.add(isGlutenFree, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 107, -1));

        noOfServings.setEnabled(false);
        noOfServings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfServingsActionPerformed(evt);
            }
        });
        jPanel1.add(noOfServings, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 107, -1));

        noOfServingsjLabel.setText("No. of Servings");
        jPanel1.add(noOfServingsjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        recipeTitlejLabel.setText("Recipe Title");
        jPanel1.add(recipeTitlejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        recipeTitle.setEnabled(false);
        recipeTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeTitleActionPerformed(evt);
            }
        });
        jPanel1.add(recipeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 107, -1));

        descriptionjLabel.setText("Description");
        jPanel1.add(descriptionjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        categoryOfFoodjLabel.setText("Category of Food");
        jPanel1.add(categoryOfFoodjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 730, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void categoryOfFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryOfFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryOfFoodActionPerformed

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionActionPerformed

    private void noOfIngredientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfIngredientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfIngredientsActionPerformed

    private void difficultylvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultylvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_difficultylvActionPerformed

    private void isGlutenFreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isGlutenFreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isGlutenFreeActionPerformed

    private void noOfServingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfServingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfServingsActionPerformed

    private void recipeTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recipeTitleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categoryOfFood;
    private javax.swing.JLabel categoryOfFoodjLabel;
    private javax.swing.JTextField description;
    private javax.swing.JLabel descriptionjLabel;
    private javax.swing.JLabel difficultyLeveljLabel;
    private javax.swing.JTextField difficultylv;
    private javax.swing.JLabel emailIDjLabel;
    private javax.swing.JTextField emailId;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel firstNamejLabel;
    private javax.swing.JTextField isGlutenFree;
    private javax.swing.JLabel isGlutenFreejLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lastNamejLabel;
    private javax.swing.JTextField noOfIngredients;
    private javax.swing.JLabel noOfIngredientsjLabel;
    private javax.swing.JTextField noOfServings;
    private javax.swing.JLabel noOfServingsjLabel;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phonejLabel;
    private javax.swing.JLabel recipePicturejLabel;
    private javax.swing.JTextField recipeTitle;
    private javax.swing.JLabel recipeTitlejLabel;
    private javax.swing.JTextField userName;
    private javax.swing.JLabel userNamejLabel;
    // End of variables declaration//GEN-END:variables
}
