/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Model.Person;
import Model.Contact;
import Model.Recipe;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author siqiyang
 */
public class UpdateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
    
    private Person person;
    private Boolean validate = false;
    private String picture = "";
    
    public UpdateJPanel(Person person) {
        initComponents();
        this.person =person;
        displayPerson(person);
    }
    
    private void displayPerson(Person person){
        String firstName1 = person.getFirstName();
        firstName.setText(firstName1);
        
        String lastName1 = person.getLastName();
        lastName.setText(lastName1);
        
        String username = person.getUserName();
        userName.setText(username);
        
        Contact contact = this.person.getContact();
        emailId.setText(contact.getEmailId());
        phone.setText(String.valueOf(contact.getPhone()));
    
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstName = new javax.swing.JTextField();
        firstNamejLabel = new javax.swing.JLabel();
        lastNamejLabel = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        userNamejLabel = new javax.swing.JLabel();
        emailIDjLabel = new javax.swing.JLabel();
        emailId = new javax.swing.JTextField();
        phonejLabel = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        categoryOfFood = new javax.swing.JTextField();
        categoryOfFoodjLabel = new javax.swing.JLabel();
        noOfIngredientsjLabel = new javax.swing.JLabel();
        noOfIngredients = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        descriptionjLabel = new javax.swing.JLabel();
        recipeTitle = new javax.swing.JTextField();
        recipeTitlejLabel = new javax.swing.JLabel();
        noOfServingsjLabel = new javax.swing.JLabel();
        noOfServings = new javax.swing.JTextField();
        isGlutenFree = new javax.swing.JTextField();
        isGlutenFreejLabel = new javax.swing.JLabel();
        difficultyLeveljLabel = new javax.swing.JLabel();
        difficultylv = new javax.swing.JTextField();
        updateRecipeBtn = new javax.swing.JButton();
        imageUploadBtn = new javax.swing.JButton();
        recipePicturejLabel = new javax.swing.JLabel();
        headtitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(188, 221, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstName.setEnabled(false);
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 108, 85, -1));

        firstNamejLabel.setText("Chef’s First Name");
        add(firstNamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 111, -1, -1));

        lastNamejLabel.setText("Chef’s Last Name");
        add(lastNamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 146, -1, -1));

        lastName.setEnabled(false);
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 143, 85, -1));

        userName.setEnabled(false);
        add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 108, 85, -1));

        userNamejLabel.setText("Username");
        add(userNamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 111, -1, -1));

        emailIDjLabel.setText("Email ID");
        add(emailIDjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 146, -1, -1));

        emailId.setEnabled(false);
        add(emailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 143, 85, -1));

        phonejLabel.setText("Phone Number");
        add(phonejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 111, -1, -1));

        phone.setEnabled(false);
        add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 108, 85, -1));

        categoryOfFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryOfFoodActionPerformed(evt);
            }
        });
        add(categoryOfFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 213, 107, -1));

        categoryOfFoodjLabel.setText("Category of Food");
        add(categoryOfFoodjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 216, -1, -1));

        noOfIngredientsjLabel.setText("No. of Ingredients");
        add(noOfIngredientsjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 257, -1, -1));

        noOfIngredients.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                noOfIngredientsFocusLost(evt);
            }
        });
        noOfIngredients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfIngredientsActionPerformed(evt);
            }
        });
        add(noOfIngredients, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 254, 107, -1));

        description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionActionPerformed(evt);
            }
        });
        add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 382, 107, -1));

        descriptionjLabel.setText("Description");
        add(descriptionjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 382, -1, -1));

        recipeTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                recipeTitleFocusLost(evt);
            }
        });
        recipeTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeTitleActionPerformed(evt);
            }
        });
        add(recipeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 213, 107, -1));

        recipeTitlejLabel.setText("Recipe Title");
        add(recipeTitlejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 216, -1, -1));

        noOfServingsjLabel.setText("No. of Servings");
        add(noOfServingsjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 257, -1, -1));

        noOfServings.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                noOfServingsFocusLost(evt);
            }
        });
        noOfServings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfServingsActionPerformed(evt);
            }
        });
        add(noOfServings, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 254, 107, -1));

        isGlutenFree.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                isGlutenFreeFocusLost(evt);
            }
        });
        isGlutenFree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isGlutenFreeActionPerformed(evt);
            }
        });
        add(isGlutenFree, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 295, 107, -1));

        isGlutenFreejLabel.setText("Is Gluten Free ");
        add(isGlutenFreejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 298, -1, -1));

        difficultyLeveljLabel.setText("Difficulty Level ");
        add(difficultyLeveljLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 339, -1, -1));

        difficultylv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                difficultylvFocusLost(evt);
            }
        });
        difficultylv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultylvActionPerformed(evt);
            }
        });
        add(difficultylv, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 336, 107, -1));

        updateRecipeBtn.setText("Update Recipe");
        updateRecipeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRecipeBtnActionPerformed(evt);
            }
        });
        add(updateRecipeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 443, -1, -1));

        imageUploadBtn.setText("Upload Images");
        imageUploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageUploadBtnActionPerformed(evt);
            }
        });
        add(imageUploadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        recipePicturejLabel.setBackground(new java.awt.Color(204, 204, 0));
        add(recipePicturejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 180, 120));

        headtitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        headtitle.setText("Recipe Update");
        add(headtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void categoryOfFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryOfFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryOfFoodActionPerformed

    private void noOfIngredientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfIngredientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfIngredientsActionPerformed

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionActionPerformed

    private void recipeTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recipeTitleActionPerformed

    private void noOfServingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfServingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfServingsActionPerformed

    private void isGlutenFreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isGlutenFreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isGlutenFreeActionPerformed

    private void difficultylvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultylvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_difficultylvActionPerformed

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void updateRecipeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRecipeBtnActionPerformed
        // TODO add your handling code here
        
        String recipeTitle1 = recipeTitle.getText();
        String categoryOfFood1 = categoryOfFood.getText();
        String noOfServings1 = noOfServings.getText();
        String isGlutenFree1 = isGlutenFree.getText();
        String difficultylv1 = difficultylv.getText();
        String noOfIngredients1 = noOfIngredients.getText();
        String description1 = description.getText();
        String recipePhoto1= picture;
        

        
        if(recipeTitle1.isBlank()|| categoryOfFood1.isBlank() || description1.isBlank()||noOfServings1.isBlank()
                ||isGlutenFree1.isBlank() || difficultylv1.isBlank()||noOfIngredients1.isBlank()||recipePhoto1.isBlank()){
        this.validate = true;
            JOptionPane.showMessageDialog(null, "Pleae fill all fields");
        } else {
                    
                Recipe recipe = this.person.getRecipe();
                recipe.setRecipeTitle(recipeTitle1);
                recipe.setCategoryOfFood(categoryOfFood1);
                recipe.setDescription(description1);
                recipe.setDifficultyLevel(Double.valueOf(difficultylv1));
                recipe.setNoOfIngredient(Integer.valueOf(noOfIngredients1));
                recipe.setNoOfServings(Integer.valueOf(noOfServings1));
                recipe.setIsGlutenFree(Boolean.valueOf(isGlutenFree1));
                recipe.setRecipePicture(picture);
 
                JOptionPane.showMessageDialog(null, "Information Updated");
        
        }
    }//GEN-LAST:event_updateRecipeBtnActionPerformed

    private void imageUploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageUploadBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();

        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);

        if(showOpenDialogue ==JFileChooser.APPROVE_OPTION){
            File selectedImageFile = browseImageFile.getSelectedFile();
            String recipePicture = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null,recipePicture);

            ImageIcon ii= new ImageIcon(recipePicture);

            Image image = ii.getImage().getScaledInstance(recipePicturejLabel.getWidth(), recipePicturejLabel.getHeight(),Image.SCALE_SMOOTH);

            recipePicturejLabel.setIcon(new ImageIcon(image));
            
            picture = recipePicture;
        }

    }//GEN-LAST:event_imageUploadBtnActionPerformed

    private void recipeTitleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_recipeTitleFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_recipeTitleFocusLost

    private void noOfServingsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_noOfServingsFocusLost
        // TODO add your handling code here:
                if(noOfServings.getText().isEmpty()) {
            // error
            
            this.validate = true;
            
        } else {
            if(noOfServings.getText().matches("\\d+")) {
                this.validate = false;
            } else {
                this.validate = true;
                noOfServings.setText("");
            }
        }
    }//GEN-LAST:event_noOfServingsFocusLost

    private void isGlutenFreeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_isGlutenFreeFocusLost
        // TODO add your handling code here:
        if(isGlutenFree.getText().isEmpty()) {
            // error
            
            this.validate = true;
            
        } else {
            if(isGlutenFree.getText().equalsIgnoreCase("true") ||isGlutenFree.getText().equalsIgnoreCase("false")  ) {
                this.validate = false;
            } else {
                this.validate = true;
                isGlutenFree.setText("");
            }
        }
    }//GEN-LAST:event_isGlutenFreeFocusLost

    private void difficultylvFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_difficultylvFocusLost
        // TODO add your handling code here:
        if(difficultylv.getText().isEmpty()) {
            // error
            
            this.validate = true;
            
        } else {
            if(difficultylv.getText().matches("\\d+")) {
                this.validate = false;
            } else {
                this.validate = true;
                difficultylv.setText("");
            }
        }
    }//GEN-LAST:event_difficultylvFocusLost

    private void noOfIngredientsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_noOfIngredientsFocusLost
        // TODO add your handling code here:
        if(noOfIngredients.getText().isEmpty()) {
            // error
            
            this.validate = true;
            
        } else {
            if(noOfIngredients.getText().matches("\\d+")) {
                this.validate = false;
            } else {
                this.validate = true;
                noOfIngredients.setText("");
            }
        }
    }//GEN-LAST:event_noOfIngredientsFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categoryOfFood;
    private javax.swing.JLabel categoryOfFoodjLabel;
    private javax.swing.JTextField description;
    private javax.swing.JLabel descriptionjLabel;
    private javax.swing.JLabel difficultyLeveljLabel;
    private javax.swing.JTextField difficultylv;
    private javax.swing.JLabel emailIDjLabel;
    private javax.swing.JTextField emailId;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel firstNamejLabel;
    private javax.swing.JLabel headtitle;
    private javax.swing.JButton imageUploadBtn;
    private javax.swing.JTextField isGlutenFree;
    private javax.swing.JLabel isGlutenFreejLabel;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lastNamejLabel;
    private javax.swing.JTextField noOfIngredients;
    private javax.swing.JLabel noOfIngredientsjLabel;
    private javax.swing.JTextField noOfServings;
    private javax.swing.JLabel noOfServingsjLabel;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phonejLabel;
    private javax.swing.JLabel recipePicturejLabel;
    private javax.swing.JTextField recipeTitle;
    private javax.swing.JLabel recipeTitlejLabel;
    private javax.swing.JButton updateRecipeBtn;
    private javax.swing.JTextField userName;
    private javax.swing.JLabel userNamejLabel;
    // End of variables declaration//GEN-END:variables
}
